version: '3'

services:
  clock-app:
    build: ./clockApp
    ports:
      - "8000:8000"
    networks:
      - clock-net

  # pong-app:
  #   build: ./pong-app
  #   ports:
  #     - "8001:8000"
  #   networks:
  #     - pong-net

networks:
  clock-net:
    driver: bridge

  # pong-net:
  #   driver: bridge
